### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by nozwock**
In this PR, I have focused solely on making changes related to error handling.

We are utilizing `eyre` instead of `anyhow` here because `eyre` automatically provides line and column information for errors. I haven't explored whether there is an effortless way to achieve the same with `anyhow` yet.

### CODE REVIEW

**Comment by nozwock** [comment]
Let me know anything I might've missed and take your time to review.

**Review by dvishal485 — APPROVED** [review]

**Comment by dvishal485** [comment]
Ah, accidentally approved the PR without reviewing. I will review the PR and let you know if there is anything to my concern.
Thanks a lot for you contribution! ⭐

**Review by dvishal485 — APPROVED** [review]

**Comment by nozwock** [comment]
Also, I think I removed context to some of the errors, they can be added back with `.wrap_err` if they feel relevant to you.

**Review by dvishal485 — APPROVED** [review]

**Comment by dvishal485** [comment]
> 

Yeah, sure! Most errors handled manually were something for which the default error message generated should be enough!
The relevant errors were those which dealt with cookie renewal and user's submissions, and as I can review, you already handled them with `wrap_err`.

I appreciate your contribution to this repository and for taking out time for the same.

**Pull request merged**
